### PR TITLE
Disable eslint-plugin-compat check for promises because we use babel-transform-runtime

### PR DESCRIPTION
**Pull request by steve-taylor**

### CODE REVIEW

**Comment by steve-taylor** [comment]
`eslint-plugin-compat` was previously not checking for `Promise`. We don't need this check because it's effectively polyfilled by `babel-transform-runtime`.

https://github.com/amilajack/eslint-plugin-compat/issues/97

**Review by roubaobaozi — APPROVED** [review]

**Review by seankoji — APPROVED** [review]

**Comment by darrennolan** [comment]
Can we not put this into it's own file or something?

We have several scenarios with this;

* Project uses transform runtime (we get a lot of es6-y ness, but not things like find/startsWith)
* Project uses babel polyfill (or the page is expected to do so).
* Project straight up is es6 only supported. (Internal tool or something where we dont' have IE).

Or is this the intended use of 'compat' rules?

**Comment by jimblue** [comment]
Any news about this?

**Comment by steve-taylor** [comment]
I considered only the first scenario, which has so far been our use case.

**Pull request merged**
